import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
ATLANTIC_API_KEY = os.getenv("ATLANTIC_API_KEY")
ATLANTIC_BASE_URL = "https://atlantich2h.com" 

ADMIN_IDS = [8372210994] 

user_states = {}
reff_id_to_chat_id_map = {}

# Definisi State Pengguna
USER_STATE_MENU_MAIN = 0
USER_STATE_ENTER_PHONE = 1
USER_STATE_ENTER_OTP = 2
USER_STATE_SELECTING_PACKAGE = 4
USER_STATE_CONFIRM_PURCHASE = 5
USER_STATE_SELECTING_PAYMENT_METHOD = 6
USER_STATE_SELECTING_EWALLET = 7
USER_STATE_ENTER_EWALLET_NUMBER = 8
USER_STATE_ENTER_TOPUP_AMOUNT = 9
USER_STATE_ADMIN_TOPUP_NUMBER = 10
USER_STATE_ADMIN_TOPUP_AMOUNT = 11
USER_STATE_ADMIN_SWITCH_NUMBER = 12
# --- STATE BARU DITAMBAHKAN DI SINI ---
USER_STATE_ENTER_DEPOSIT_ID = 13
USER_STATE_AWAIT_MANUAL_PROOF= 14